import ProviderNext from '@/components/ProviderNext'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const inter = Poppins({ subsets:  ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]})

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
  icons: {
    apple: 'https://i.imgur.com/7DMwJ3Y.png'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="light" lang="en">
      <body className={`overflow-x-hidden ${inter.className}`}>
      <ProviderNext>
        {children}
      </ProviderNext>
      </body>
    </html>
  )
}
